version: '3.7'

services:
  jupyter:
    container_name: 'gabriel-tiveron-jupyter'
    image: 'tiverons/jupyternotebook'
    build:
      context: ./notebooks
      dockerfile: Dockerfile
    volumes:
      - "./:/notebooks"
    ports:
      - "8888:8888"
